tap "gromgit/fuse"

brew "ack"
brew "brew-cask-completion"
brew "git-delta"
brew "fish"
brew "fzf"
brew "git"
brew "gnupg"
brew "gromgit/fuse/sshfs-mac"
brew "htop"
brew "imagemagick"
brew "jq"
brew "moreutils" # includes vipe
brew "nmap"
brew "openssh"
brew "openssl"
brew "reattach-to-user-namespace"
brew "rsync"
brew "shpotify"
brew "tmux"
brew "tree"
brew "unzip"
brew "watchman"
brew "wget"
brew "vim"
brew "youtube-dl"

cask "alfred"
cask "bettertouchtool"
cask "itsycal"
cask "discord"
cask "docker"
cask "electrum"
cask "forklift"
cask "firefox"
cask "karabiner-elements"
cask "kitty"
cask "macfuse"
cask "monitorcontrol"
cask "nextcloud"
cask "rectangle"
cask "slack"
cask "spotify"
cask "tor-browser"
cask "transmission"
cask "vlc"

mas "amphetamine", id: 937984704
