tap "gromgit/fuse"
brew "ack"
brew "autossh"
brew "brew-cask-completion"
brew "fish"
brew "fzf"
brew "getmail"
brew "git"
brew "gnupg"
brew "graphviz"
brew "imagemagick"
brew "jq"
brew "openssh"
brew "openssl"
brew "rsync"
brew "shpotify"
brew "gromgit/fuse/sshfs-mac"
brew "tmux"
brew "tree"
brew "unzip"
brew "watchman"
brew "wget"
brew "youtube-dl"
brew "reattach-to-user-namespace"
brew "docker"
brew "blueutil"

cask "firefox"
cask "alfred"
cask "spotify"
cask "iterm2"
cask "electrum"
cask "bettertouchtool"
cask "monitorcontrol"

mas "amphetamine", id: 937984704
